### ISSUE TITLE
The No context item text in the sidebar within the context perspective is black, hideous. 

### ISSUE THREAD

**Issue by kingmatusevich** [ZeFish/Iris-Theme-OmniFocus#2]

**Comment by ZeFish** [comment]
Here's the hideous again.... Seriously? (don't answer)

That text use the same "Strong Text Color" and is used for editing content and also the header text in the main view. Now that the left sidebar is darker. It's not possible to make all those content readable with their background. I've written an email to OmniGroup about it. If they fix it... I will update the theme.
